> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Fundmental Numpy Functions: Array Manipulation Routines

1. `reshape(a, newshape[, order])`
    - Gives a new shape to an array without changing its data.
2. `concatenate([axis, out, dtype, casting])`
    - Join a sequence of arrays along an existing axis.
3. `roll(a, shift[, axis])`
    - Roll array elements along a given axis.
4. `split(ary, indices_or_sections[, axis])`
    - Split an array into multiple sub-arrays.
5. `flip(m[, axis])`
    - Reverse the order of elements in an array along the given axis.

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
%pip install jovian --upgrade -q

Note: you may need to restart the kernel to use updated packages.


In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
project, filename = 'numpy-array-operations', 'numpy-array-operations.ipynb'

In [4]:
# jovian.commit(project='numpy-array-operations', filename=filename, privacy='secret')

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [5]:
import numpy as np

In [26]:
# List of functions explained 
function1 = np.reshape
function2 = np.concatenate
function3 = np.roll
function4 = np.split
function5 = np.flip

## Function 1 - np.reshape

This function allows us to reshap a numpy array without changing the data in the array. 

In [7]:
# Example 1 - working
arr1 = np.array([[4, 5, 6], [7, 8, 9]])
arr1 = np.reshape(arr1, (3, 2))
arr1

array([[4, 5],
       [6, 7],
       [8, 9]])

#### Explanation about example
Here we take `arr1`, which has a shape of `(2, 3)` and pass it thorugh the reshape function to change the shape of the array to `(3, 2)`

In [8]:
# Example 2 - working
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.reshape(arr2, (3, -1))
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

#### Explanation about example
Here we take arr2, which has the shape of `(2, 3)` (just has our last array). This time though, when we pass the array thorugh the reshape function, we set our second digit in the shape tuple to `-1`. This sets the axis as undefined, based on the amount elements in the array, Numpy assumes that the undefined vale is `2`.

In [9]:
# Example 3 - breaking (to illustrate when it breaks)
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.reshape(arr3, (3, 3))

ValueError: cannot reshape array of size 6 into shape (3,3)

#### Explanation about example (why it breaks and how to fix it)
Here we break the reshape function by passing it and invalid shape for the array size. We must ensure that the shape the we wish to reshape to is a valid shape for the array size. <br>
<br>
To fix this, we could either change our second axis to `2` as we know this would be a valid shape. If we are unsure of what to set the axis to to create a valid shape, we can pass `-1` also known as `undefined` to the axis and Numpy will attempt to provide us with a valid shape for our array size. 

#### Some closing comments about when to use this function.
This function is very useful when we need to change the demenstions of an array as it allows us to set the shape, which inter changes the demenstions of the array. We could make a 1D array 2D or even 3D and vice versa. 

In [ ]:
# jovian.commit(project=project, filename=filename)

## Function 2 - np.concatenate

This function allows you to join any number of arrays along your requested, existing, axis. 

In [10]:
# Example 1 - working
arr1 = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr2 = np.array([[15, 16, 17, 18, 20, 21]])
arr3 = np.concatenate((arr1, arr2))
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [15, 16, 17, 18, 20, 21]])

#### Explanation about example
Here we join `arr1` and `arr2` to create `arr3`. As we did not provied an axis argument, the default axis of 0 is used when concatenating. 

In [11]:
# Example 2 - working
arr1 = ([[1, 2, 3], [4, 5, 6]])
arr2 = ([[7, 8, 9], [10, 11, 12]])
arr3 = np.concatenate((arr1, arr2), axis=1)
arr4 = np.concatenate((arr1, arr2), axis=0)
arr3, arr4

(array([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

#### Explanation about example
Here we use the axis argument to join the arrays on the first axis (or demension). We use `arr4` to demenstrate the difference and to bettery show how the arrays are joined upon the specified axis. 

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])
arr3 = np.concatenate((arr1, arr2))
arr3

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4

#### Explanation about example (why it breaks and how to fix it)
Here we attempt to concatenate 2 arrays of different shapes. As the error states, the array demensions MUST match EXACTLY. To reslove this issue we either neet to pass an array of the correct shape into concatenate, or we need to resahpe our array to match the shape of the array we wish to concatenate with. 

In [ ]:
# jovian.commit(filename=filename, project=project)

## Function 3 - np.roll

This function allows you to roll elements from the end of an array to the front of the array along any given demension

In [28]:
# Example 1 - working
arr1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr2 = np.roll(arr1, 2)
arr2

array([[7, 8, 1, 2],
       [3, 4, 5, 6]])

#### Explanation about example
Here we call `np.roll` on `arr1` passing in 2 as our shift arg. This causes numpy to roll the last element in the array to the front of the array twice. Resulting in an array that reminds us of a rotated sorted list.

In [38]:
# Example 2 - working
arr1 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]])
arr2 = np.roll(arr1, 2)
arr3 = np.roll(arr1, 2, axis=1)
print(arr2)
print(arr3)

[[9 0 1 2 3]
 [4 5 6 7 8]]
[[4 5 1 2 3]
 [9 0 6 7 8]]


#### Explanation about example
Here we show what happens when the axis of our roll is defined. In `arr1` we show the roll from example 1. As expected, our 2 rolls happen upon all demension. In `arr3` we define the arg `axis=1`, this causes our roll to only happen on the 1st demension.

In [41]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr2 = np.roll(arr1, 5, axis=1)
arr2

AxisError: axis 1 is out of bounds for array of dimension 1

#### Explanation about example (why it breaks and how to fix it)
Here we break this function by providing it with an axis arg that is out of bounds for the demensions of our current array. To fix this, we need to ensure that we are defining a valid axis, either buy change the current axis arg, or by reshaping our array. 

##### Some closing comments about when to use this function.
This function is very useful if we need to shift the elements in our array for any reason, as not only does in maintain the data in the array, but also the arrays shape. This makes is quick and simple if we need to shift our array any amount of times.

In [42]:
# jovian.commit(project=project, filename=filename)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zoibderg/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/zoibderg/numpy-array-operations


'https://jovian.ai/zoibderg/numpy-array-operations'

## Function 4 - np.split

Split an array into multiple sub-arrays.
If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis. If such a split is not possible, an error is raised.

In [47]:
# Example 1 - working
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr2 = np.split(arr1, 2)
arr2

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9, 0])]

#### Explanation about example
Here we show a simple example of the split function, splitting a 1D array in half to create 2 1D arrays.

In [49]:
# Example 2 - working
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2 =np.split(arr1, [2, 6])
arr2

[array([1, 2]), array([3, 4, 5, 6]), array([7, 8])]

#### Explanation about example
WHen the split function is passed a 1-D array of sorted integers, the entries indicate where along axis the array is split. Here we pass the sorted integers `[2, 6]`. This will cause the array to be split along spesific elements along the axis;<br>
<br>
arr[:2]<br>
arr[2:6]<br>
arr[6:]<br>

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])
arr2 = np.split(arr1, 4)

ValueError: array split does not result in an equal division

#### Explanation about example (why it breaks and how to fix it)
Here we attempt to split an array that has 10 elements, 4 times. This does not provied equal groups, therefore we are given a ValueError, as our array split must result in equal division. To solve this issue, you could either pass an intiger that woudl split the array equal times, or you could use the above argument and pass sorted pairs to the split to get your desired split. 

##### Some closing comments about when to use this function.
This function is great any time that you need to split an array into smaller arrays for any reason. This function is great as it not only keeps our data intact, but also keeps the shape of our array intact as well. This makes working our our arrays much simpler. 

In [51]:
# jovian.commit(project=project, filename=filename)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zoibderg/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/zoibderg/numpy-array-operations


'https://jovian.ai/zoibderg/numpy-array-operations'

## Function 5 - np.flip

This funciton reverses the elements in an array along the given axies; shape is preserved, while elements are reordered. 

In [52]:
# Example 1 - working
arr1 = np.arange(8).reshape((2,2,2))
arr2 = np.flip(arr1, 0)
print(arr1)
print(arr2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[4 5]
  [6 7]]

 [[0 1]
  [2 3]]]


#### Explanation about example
Here we flip our array along axis 0. This is a up/down flip where everything in the 0th demension is reversed. 

In [53]:
# Example 2 - working
arr3 = np.flip(arr1, 2)
arr3

array([[[1, 0],
        [3, 2]],

       [[5, 4],
        [7, 6]]])

#### Explanation about example
Here we flip the array along the 2nd axis. This causes all elements in the array to be reversed within their axis. 

In [54]:
# Example 3 - breaking (to illustrate when it breaks)
arr4 = np.flip(arr1, 3)

AxisError: axis 3 is out of bounds for array of dimension 3

##### Explanation about example (why it breaks and how to fix it)
As expected, you cannot flip an axis that is out of bounds for whatever demension that you are working with. To solve this, you either need to pass a valid axis, or reshape your array. 

In [55]:
# jovian.commit(project=project, filename=filename)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zoibderg/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/zoibderg/numpy-array-operations


'https://jovian.ai/zoibderg/numpy-array-operations'

## Conclusion

#### Summarize what was covered in this notebook, and where to go next.
In this note book I went over some basic functions for Array Manipulation to help build a better understand of how Numpy arrays function. Next I will expand knowlage of Numpy further by practicing the 100 Numpy problems notebook. I will look to be able to complete 20 - 30 of the problems within. 

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [56]:
jovian.commit(project=project, filename=filename)

<IPython.core.display.Javascript object>

[jovian] Updating notebook "zoibderg/numpy-array-operations" on https://jovian.ai/
[jovian] Committed successfully! https://jovian.ai/zoibderg/numpy-array-operations


'https://jovian.ai/zoibderg/numpy-array-operations'